AWSTemplateFormatVersion: '2010-09-09'
Description: 'IT-Academy

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/student/
Resources:
  Login:
    Properties:
      CodeUri: s3://it-academy-lambda/f248b1e64842ba6d7e55d13c5672e027
      Environment:
        Variables:
          ENDPOINT: dynamodb.us-east-1.amazonaws.com
          REGION: us-east-1
      Events:
        login:
          Properties:
            Method: post
            Path: /login
          Type: Api
      Handler: app.lambdaHandler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OptionStudent:
    Properties:
      CodeUri: s3://it-academy-lambda/f6e13f26741a38485b0fa5f3ee70a387
      Events:
        OptionStudent:
          Properties:
            Method: options
            Path: /student
          Type: Api
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  SaveStudent:
    Properties:
      CodeUri: s3://it-academy-lambda/8808dfc95dbf7cfe7f0e800413637778
      Environment:
        Variables:
          ENDPOINT: dynamodb.us-east-1.amazonaws.com
          REGION: us-east-1
      Events:
        SaveStudent:
          Properties:
            Method: post
            Path: /student
          Type: Api
      Handler: app.lambdaHandler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  SecretTable:
    Properties:
      PrimaryKey:
        Name: key
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Secret
    Type: AWS::Serverless::SimpleTable
  StudentTable:
    Properties:
      PrimaryKey:
        Name: regNo
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Student
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
