AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    IT-Academy

    
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

#LAMBDA SECTION

    SaveStudent:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: save_students/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Policies: AmazonDynamoDBFullAccess
            Environment:
                Variables:
                    ENDPOINT: dynamodb.us-east-1.amazonaws.com
                    REGION: us-east-1

            Events:
                SaveStudent:
                    Type: Api
                    Properties:
                        Path: /student
                        Method: post
            
    OptionStudent:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: option_student/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Events:
                OptionStudent:
                    Type: Api
                    Properties:
                        Path: /student
                        Method: options

    Login:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: login/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Policies: AmazonDynamoDBReadOnlyAccess
            Environment:
                Variables:
                    ENDPOINT: dynamodb.us-east-1.amazonaws.com
                    REGION: us-east-1
            Events:
                login:
                    Type: Api
                    Properties:
                        Path: /login
                        Method: post                         

# TABLE SECTION
    StudentTable:
        Type: AWS::Serverless::SimpleTable   
        Properties: 
            TableName: Student
            PrimaryKey:
                Name: regNo
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

    SecretTable:
        Type: AWS::Serverless::SimpleTable   
        Properties: 
            TableName: Secret
            PrimaryKey:
                Name: key
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1                
Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/student/"


