AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    IT-Academy

    
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:
    SaveStudent:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: save_students/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Policies: AmazonDynamoDBFullAccess
            Events:
                SaveStudent:
                    Type: Api
                    Properties:
                        Path: /save
                        Method: post
                OptionStudent:
                    Type: Api
                    Properties:
                        Path: /save
                        Method: options
                                   

    StudentTable:
        Type: AWS::Serverless::SimpleTable   
        Properties: 
            TableName: Student
            PrimaryKey:
                Name: regNo
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"


